github: [ValeriiVasyliev]
bitcoin: 3PsnpooUyz1ePJdANkhq6S9G6wneNvCAFw
ethereum: 0xd927784cd35092d47eaa40847202934f2a885ffa
custom: ["https://btc.com/btc/address/3PsnpooUyz1ePJdANkhq6S9G6wneNvCAFw", 3PsnpooUyz1ePJdANkhq6S9G6wneNvCAFw]
